[book]
title = "AsterClaw Documentation"
authors = ["FerrisMind"]
language = "ru"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/FerrisMind/AsterClaw"
edit-url-template = "https://github.com/FerrisMind/AsterClaw/edit/main/docs/{path}"

[output.html.fold]
enable = true
level = 1
